chaos:
  cpu-burner:
    enabled: false
    step: 0.2
    duration: 10000
  pid-burner:
    enabled: false
    max-threads: 200
    duration: 100
  ram-burner:
    enabled: false
    max-memory: 2000
    duration: 100

logging:
  level:
    fr.fillatre.testing.chaoscontainer.nutjobs: DEBUG
