chaos:
  cpu-burner:
    enabled: false
    step: 0.2
    duration: 10000
  fio-burner:
    enabled: false
    max-files: 1
    file-size: 1000
    throughput: 100
  log-burner:
    enabled: false
    max-logs: 10
    logs-per-sec: 100
  pid-burner:
    enabled: false
    max-threads: 200
    duration: 100
  ram-burner:
    enabled: false
    max-memory: 2000
    duration: 100

logging:
  level:
    fr.fillatre.testing.chaoscontainer.nutjobs: DEBUG
